export default [
  {
    tableIndex: 1,
    persons: 2,
    startTime: "14:00:00",
    food: [
      { foodname: "크림 파스타", count: 1, amount: 10000 },
      { foodname: "로제 파스타", count: 1, amount: 10000 },
      { foodname: "탄산 음료", count: 1, amount: 1000 },
      { foodname: "마라탕", count: 1, amount: 10000 },
      { foodname: "대합탕", count: 1, amount: 20000 },
      { foodname: "냉동 삽겸살", count: 5, amount: 20000 },
      { foodname: "계란 말이", count: 5, amount: 20000 },
    ],
    totalAmount: 21000,
  },
  {
    tableIndex: 2,
    persons: 2,
    startTime: "14:00:00",
    food: [
      { foodname: "크림 파스타", count: 1, amount: 10000 },
      { foodname: "로제 파스타", count: 1, amount: 10000 },
      { foodname: "탄산 음료", count: 1, amount: 1000 },
    ],
    totalAmount: 21000,
  },
  {
    tableIndex: 3,
    persons: 2,
    startTime: "14:00:00",
    food: [
      { foodname: "크림 파스타", count: 1, amount: 10000 },
      { foodname: "로제 파스타", count: 1, amount: 10000 },
      { foodname: "탄산 음료", count: 1, amount: 1000 },
    ],
    totalAmount: 21000,
  },
  {
    tableIndex: 4,
    persons: 0,
    startTime: "00:00:00",
    food: [],
    totalAmount: 0,
  },
  {
    tableIndex: 5,
    persons: 0,
    startTime: "00:00:00",
    food: [],
    totalAmount: 0,
  },
  {
    tableIndex: 6,
    persons: 0,
    startTime: "00:00:00",
    food: [],
    totalAmount: 0,
  },
  {
    tableIndex: 7,
    persons: 0,
    startTime: "00:00:00",
    food: [],
    totalAmount: 0,
  },
  {
    tableIndex: 8,
    persons: 0,
    startTime: "00:00:00",
    food: [],
    totalAmount: 0,
  },
  {
    tableIndex: 9,
    persons: 0,
    startTime: "00:00:00",
    food: [],
    totalAmount: 0,
  },
  {
    tableIndex: 10,
    persons: 0,
    startTime: "00:00:00",
    food: [],
    totalAmount: 0,
  },
  {
    tableIndex: 11,
    persons: 0,
    startTime: "00:00:00",
    food: [],
    totalAmount: 0,
  },
  {
    tableIndex: 12,
    persons: 0,
    startTime: "00:00:00",
    food: [],
    totalAmount: 0,
  },
  {
    tableIndex: 13,
    persons: 0,
    startTime: "00:00:00",
    food: [],
    totalAmount: 0,
  },
  {
    tableIndex: 14,
    persons: 0,
    startTime: "00:00:00",
    food: [],
    totalAmount: 0,
  },
  {
    tableIndex: 15,
    persons: 0,
    startTime: "00:00:00",
    food: [],
    totalAmount: 0,
  },
];
